### ISSUE TITLE
Elasticsearch 5.5.1 heap_used_percent error

### ISSUE THREAD

**Issue by metabsd** [bbb31/check-es#1]
```
[root@slpmon0039 plugins]# ./check-es -x heap_used_percent -a slpelk0675 -w 1 -c 2
Traceback (most recent call last):
  File "./check-es", line 198, in <module>
    main()
  File "./check-es", line 195, in main
    start(data, status_check, compare_val, crit_val, warn_val)
  File "./check-es", line 105, in start
    int_checker(node_data["nodes"][node_id_key]["jvm"]["mem"]["heap_used_percent"])
TypeError: int_checker() takes exactly 5 arguments (1 given)

```

**Comment by metabsd** [comment]
By the way, great work. I will use your plugin :)

**Comment by bbb31** [comment]
Apologies, I didn't get a notification for this. Can you confirm if you're still having an issue?

**Comment by bbb31** [comment]
I havent heard back from you regarding this; closing.
